### ISSUE TITLE
Keycloak v19 REGISTER_EVENT has NULL for "firstname", "lastname" after activating declarative-user-profile

### ISSUE THREAD

**Issue by marziman** [SnuK87/keycloak-kafka#18]
Hello @SnuK87 

we are a bit lost and need your advice.
We are using this extension successfully with older KC versions. Since the migration to KC v19 and after activating
the feature "declarative-user-profiles" and setting User Profile to ON in the Realm, we are getting in our Register Event NULL for both fields. 

We are trying to understand why this happens. Can it be that some SPIs and APIs used in the current implementation of the extension are now deprecated or causing this problem?

Many thanks for your help.
BR Mehmet

**Comment by SnuK87** [comment]
@marziman I'm not able to reproduce this problem with KC 19.0.2 and `DECLARATIVE_USER_PROFILE` enabled.
It was working as before during my tests.

I assume you removed the default attributes from the user profile and that's why they are not in the payload anymore. As you can see in the [code](https://github.com/SnuK87/keycloak-kafka/blob/master/src/main/java/com/github/snuk87/keycloak/kafka/KafkaEventListenerProvider.java#L66-L77), this module doesn't do anything with the event except for writing it as JSON string to kafka. This means that the register event in keycloak doesn't work with customized user profiles. Maybe that's why it's still a preview feature?
